WORKDIR set in Dockerfile and volmes for backup reasons
docpht/docpht pull request #5
Opened 2019-10-10 09:41 UTC by Shikachuu

Hey guys,
For backup and other reasons I think it is a must to mount the `pages` and `data` directory, I corrected the README.md to make it clear for everyone.

Also for relative path usage for situations like this I also make a change in the Dockerfile  and set the `WORKDIR` to `/var/www/app/`

2019-10-10 11:28 UTC, creecros approved these changes
This is fine to add

2019-10-10 11:38 UTC, creecros requested changes
I'd rather add the usage example instead of modifying the basic. Binding folders to the host is not actually necessary. I see the convenience, but know that the added bind commands would fail on my own system, therefore, it's not the basic usage.

2019-10-10 11:41 UTC, creecros commented on README.md
> +The command belowe just spins up a container for you, with backup folders from `data/` and `pages/` which contains your saved notes.
Would it not be "above" instead of "belowe", also "belowe" should be spelled "below"

2019-10-10 13:56 UTC, Shikachuu commented
> 
> 
> I'd rather add the usage example instead of modifying the basic. Binding folders to the host is not actually necessary. I see the convenience, but know that the added bind commands would fail on my own system, therefore, it's not the basic usage.

Done, thanks for the response :)

2019-10-16 15:24 UTC, kenlog commented
> No, still not what I meant.
> 
> i.e.
> Basic usage:
> Yadda yadda yadda
> 
> Example binding volumes:
> Your example...
> 
> Need to "add" your example, not modify the basic.
> 
> Make sense?

@Shikachuu

2020-01-13 11:26 UTC, closed without merging